@baseurl = https://localhost:7240/api
@rawurl = https://localhost:7240
@AccessToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0NGJjZGEzOS0xMTRkLTRhY2QtODgzYS1hYzI5YThjNDhmNGQiLCJlbWFpbCI6ImFkbWluQGJvb2tvcmJpdC5jb20iLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3NzQxODA0MDksImV4cCI6MTc3NDE4MTAwOSwiaWF0IjoxNzc0MTgwNDA5LCJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJsb2NhbGhvc3QifQ.HHQQfE8b3jA9kir1HtctrSiF0ldbOh9n_PNsEu7FfQQ
@RefreshToken = TlC/2Tld4qDTEI/JrxZeDE6MNJI55yroIs1BJw6R3Q0=

### get students - page 8 with page size 500
GET {{baseurl}}/v1.0/students?page=8&pageSize=500
Authorization: Bearer {{AccessToken}}

### get OpenApi
GET {{rawurl}}/openapi/v1.json

### get refresh token
POST {{baseurl}}/v1.0/identity/token/refresh
Content-Type: application/json

{
  "refreshToken": "{{RefreshToken}}",
  "expiredAccessToken": "{{AccessToken}}"
}


### generateToken
POST {{baseurl}}/v1.0/identity/token
Content-Type: application/json

{
  "email": "eyadreda.dev.new@std.mans.edu.eg",
  "password": "sa123456"
}


###
GET {{baseurl}}/v1.0/identity/users/me
Authorization: Bearer {{AccessToken}}




###
PUT {{baseurl}}/v1.0/students/D350784C-C542-4274-82A9-086E334D6124
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "Name": "Ali Reda one"
}


###
GET {{baseurl}}/v1.0/images/students/DefaultStudentImage.png
Authorization: Bearer {{AccessToken}}